### ISSUE TITLE
Attempting to preserve classes on click event

### ISSUE THREAD

**Issue by th3fallen** [stefanhayden/PersonalityQuizzer#1]
I'm attemting this code but as you can guess its not working

var answerModel = Model({
        init: function(){
            if(!this.get("score")) {
                this.set("score", 1);
            }
        },
        events: {
            "click >": function(e) {
                if(!quiz.get("done")) {
                    var answers = e.data.model.get("parent").get("answers");
                    var classes = $(this).attr('class');
                    $.each(answers, function(i,v){
                        v.set("selected", false);
                    });
                    $(this).removeClass('answer grid_3').addClass(classes);
                    e.data.model.set("selected", true);
                    $(e.data.model.get("parent")).trigger("answered");
                }
            }
        }
    });

What i need is to find a way to add a class of alpha and a class of omega to last one in the set is that possible if so could you please give a hand?

**Comment by stefanhayden** [comment]
you want to add it when an event happens? or just always have those classes there? Each answer has an ID you could hard code it in the template.

If you want an answer to all ways have a certain class I would just pass it in to the answer object as a value then set that value in the template. All data you pass in is accessible on the template.

so pass this data in:

``` javascript
answers: [
            { 
                text: "Tabs",
                result: 1,
                class: 'alpha',
            },
            { 
                text: "Spaces",
                result: 2,
                class: 'omega',
            },
        ]
```

and set this on the template:

``` html
<div class="answer {{#if selected}}selected{{/if}} {{#if class}} {{class}} {{/if}}" ></div>
```
