### ISSUE TITLE
Bind multiple answers to questions

### ISSUE THREAD

**Issue by th3fallen** [stefanhayden/PersonalityQuizzer#2]
Is it possible to bind multiple answers to a single question each with their own weights? if so could you please give some perspective as to where to look?

**Comment by stefanhayden** [comment]
sorry. I don't know why I keep missing these questions. 

yes. you should be able to do exactly that.

``` javascript
        answers: [
            { 
                text: "Tabs",
                result: 1,
                score: 1
            },
            { 
                text: "Tabs, no really I love tabs",
                result: 1,
                score: 10
            },
            { 
                text: "Spaces",
                result: 2
            },
        ]
```

in the above example the first 2 answers point to result 1. The 2nd has a score of 10. When a results is shown it adds up the scores from each selected answer and displays the results that has the highest tally.
