### ISSUE TITLE
Scrolltop to next question on click of an answer

### ISSUE THREAD

**Issue by buzzguy** [stefanhayden/PersonalityQuizzer#3]
Could anyone help w this code?

I tried adding:

$(document.body).animate({scrollTop: $(this).closest(".question").offset().top}, 1000);

to the answerModel below,but would like to have it go to the next '.question'. 
Using .next() or .find() makes it undefined. 

var answerModel = Model({
        init: function(){
            if(!this.get("score")) {
                this.set("score", 1);
            }
        },
        events: {
            "click >": function(e) {
                if(!quiz.get("done")) {
                    var answers = e.data.model.get("parent").get("answers");
                    $.each(answers, function(i,v){
                        v.set("selected", false)
                    })
                    e.data.model.set("selected", true);
                    $(e.data.model.get("parent")).trigger("answered");
                    var windowHeight = $(window).height();
                    $(document.body).animate({
                scrollTop: $(this).closest(".question").offset().top
            }, 1000);
                }
            }
        }
    });

**Comment by stefanhayden** [comment]
I can give it a look. I'm about to go on vacation so I might be low to get to it. just a heads up! thanks for trying it out.

**Comment by buzzguy** [comment]
thanks! it's a very nice quiz

**Comment by buzzguy** [comment]
actually, I found some code that would work

```
    var container = $(this).parent();

    // if I am the last .container in my group...
    while (    document != container[0] // not reached root
            && container.find('~.question, ~:has(.question)').length == 0)
       var container = container.parent(); // search siblings of parent instead

    var nextdiv = container.nextAll('.question, :has(.question)').first();

    // no next .container found, go back to first container
    /* if (nextdiv.length==0) nextdiv = $(document).find('.question:first'); */

    $('body').animate({scrollTop:nextdiv.offset().top-110},1000);
    // $(this).parent().next() // this is the next div container.
    return false;
```
