### ISSUE TITLE
Multiples values for each answer object?

### ISSUE THREAD

**Issue by buzzguy** [stefanhayden/PersonalityQuizzer#4]
Hi, 
I was wondering if it's possible to place multiple results for each answer?
for example:

```
result: [2,3]
```

**Comment by stefanhayden** [comment]
hmm... that seems like it would be pretty easy to do. Let me take a look tonight. thanks for the feedback!

**Comment by buzzguy** [comment]
thanks!

**Comment by stefanhayden** [comment]
I've updated things so you can pass in an array just like you suggested. would love to see a link to what you are making!

**Comment by buzzguy** [comment]
many thanks! find out what book you should read ^_^
http://www.purewow.com/entry_detail/national/11841/Quiz-What-book-should-you-read-next.htm
