### ISSUE TITLE
 Is it possible to have different answers with different choices?  

### ISSUE THREAD

**Issue by britomarco** [stefanhayden/PersonalityQuizzer#6]
Example: If he chooses 1,3,4,5 - does a specific result appear?

**Comment by stefanhayden** [comment]
each answer can only correspond to one result. at the end it just counts up which result had the most corresponding answers.

**Comment by britomarco** [comment]
Is it possible to do with weighted average?

**Comment by stefanhayden** [comment]
not with the current set up. it's very dumb atm.

**Comment by britomarco** [comment]
Yes, it was a customer request. Thank you!
